### PR TITLE
Adding avatar field on user table

### PR DESCRIPTION
**Pull request by hugoleodev**

### CODE REVIEW

**Comment by nicolasiensen** [comment]
Amazing work! Two things to add to this pull request:
* Add a thumb version to the AvatarUploader to crop images to fill 100x100px
* Add the thumb URL to the returning user JSON served by the API (try using [ActiveModel::Serializer](https://github.com/rails-api/active_model_serializers))

**Comment by nicolasiensen** [comment]
@hugoleodev posso fazer o review?

**Comment by hugoleodev** [comment]
Pode sim @nicolasiensen

**Comment by josiasds** [comment]
Merged! Thanks @hugoleodev :beers:

**Comment by nicolasiensen** [comment]
:tada:

**Pull request merged**
